spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: precious
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: joemrk1960@gmail.com
    password: zoqm fwgi yxwx juro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true  # Ensures the connection must use STARTTLS
          ssl:
            protocols: TLSv1.2  # Specifies the SSL protocols
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          trust: "*"  # Trust all certificates (use cautiously)

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

server:
  port: 8000
